"""Add play history update datetime to users

Revision ID: 098938c6cc3e
Revises: 88e58e97c207
Create Date: 2020-04-05 17:32:22.431488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '098938c6cc3e'
down_revision = '88e58e97c207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tracks_id_uniq', 'Tracks', ['id'])
    op.add_column('Users', sa.Column('last_play_history_upd', sa.DateTime(), nullable=True))
    op.create_unique_constraint('users_id_uniq', 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_id_uniq', 'Users', type_='unique')
    op.drop_column('Users', 'last_play_history_upd')
    op.drop_constraint('tracks_id_uniq', 'Tracks', type_='unique')
    # ### end Alembic commands ###
