"""Add create timestamp to tracks

Revision ID: 11dd78509ae4
Revises: d324a5d8c310
Create Date: 2020-04-11 12:56:07.820877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11dd78509ae4'
down_revision = 'd324a5d8c310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tracks', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('tracks_id_uniq', 'Tracks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tracks_id_uniq', 'Tracks', ['id'])
    op.drop_column('Tracks', 'timestamp')
    # ### end Alembic commands ###
