"""Create tracks and users table

Revision ID: a79965ad24b0
Revises: 
Create Date: 2020-03-30 11:28:42.987266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a79965ad24b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tracks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artist', sa.String(length=32), nullable=True),
    sa.Column('preview_url', sa.String(length=120), nullable=True),
    sa.Column('artist_id', sa.String(length=32), nullable=False),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('key', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('mode', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumnetalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.String(length=120), nullable=True),
    sa.Column('refresh_token', sa.String(length=120), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Tracks')
    # ### end Alembic commands ###
